Minor updates
waldronlab/SingleCellMultiModal pull request #31
Opened 2021-03-18 09:21 UTC by cvanderaa

Hi Marcel @LiNk-NY ,

This is a very small PR to change 2 small things:

- The assays in the `macrophage_differentiation` project (SCoPE2) were called `macrophage_protein` and `macrophage_rna`. Laurent pointed out to me that this can be confusing because monocyte data are also present in the assays. I renamed the assays using the project abbreviation `macroph_diff_protein` and `macroph_diff_rna`.
- I adapted the vignette with the new assay names and fixed some typos.

2021-03-18 13:10 UTC, LiNk-NY commented
Thanks for the PR Chris, note that our new function `SingleCellMultiModal` will return an assay with a name like `macrophage_differentiation_macroph_diff_protein`, for example.

2021-03-18 13:30 UTC, cvanderaa commented
Oh sorry, I didn't see the new function. It's a great feature you implemented there! 

So, I could simply name the assays `rna` and `protein`, and once called from `SingleCellMultiModal(...)`, those will become `macrophage_differentiation_rna` and `macrophage_differentiation_protein`?

Should I also document this new way of retrieving multiple datasets in the `SCoPE2.Rmd` vignette?

2021-03-18 15:49 UTC, LiNk-NY commented
Hi Chris, @cvanderaa 

> So, I could simply name the assays `rna` and `protein`, and once called from `SingleCellMultiModal(...)`, those will become `macrophage_differentiation_rna` and `macrophage_differentiation_protein`?
 
Yes, those would be the names you get with the new function. I had to append the `DataType` to differentiate the different technologies in the assays. I should add a note about that in the documentation. 

> Should I also document this new way of retrieving multiple datasets in the `SCoPE2.Rmd` vignette?

You could but you don't have to. The function is complementary to the existing ones.

2021-03-19 11:43 UTC, cvanderaa commented
Hi Marcel @LiNk-NY ,

Thanks for the info! So, this PR simply renames the assays to `rna` and `protein` (= names of the modalities on `ExperimentHub`) and makes some slight improvements to the SCoPE2 vignette.

2021-03-19 19:44 UTC, LiNk-NY requested changes
This looks neat! If you could just remove that line that is not doing anything, we'll be good to go. Thanks!

2021-03-19 19:44 UTC, LiNk-NY commented on R/SCoPE2.R
>      names(ess_list[["experiments"]]) <-
It looks like you don't need this line anymore? @cvanderaa

2021-03-20 10:36 UTC, cvanderaa commented
Oops, sorry about that! I have removed it!

2021-03-23 18:55 UTC, LiNk-NY approved these changes

2021-03-23 19:27 UTC, merged