adding ontomap file and fixing CITEseq on Marcel's suggestions
waldronlab/SingleCellMultiModal pull request #57
Opened 2023-04-17 14:59 UTC by drighelli

fixing suggestions from the previous PR https://github.com/waldronlab/SingleCellMultiModal/pull/55

2023-04-17 20:04 UTC, LiNk-NY approved these changes
The formatting should not change if there are no code improvements. There are a few lines that are adding blanks or moving code to a new line. These are distracting and make it more difficult to review. More importantly, there are ways to reduce cyclomatic complexity by using a single operation (e.g., `Map`) regardless of the length input list (e.g., either one or two) but I will leave those for future improvement. Thanks!

2023-04-17 20:04 UTC, LiNk-NY commented on R/CITEseq.R
> +                DataClass=c("MultiAssaiExperiment", "SingleCellExperiment"),
This should be `MultiAssayExperiment`

2023-04-17 20:04 UTC, LiNk-NY commented on R/CITEseq.R
> +                                                          altExps=list(scADT=scadt,
There is code here that is just "noise" for the PR. If there are no significant changes, please do not change the spacing / formatting. It makes it harder to review.

2023-04-17 20:04 UTC, LiNk-NY commented on R/CITEseq.R
> +        if(dataClass=="SingleCellExperiment") return(.CITEseqMaeToSce(mae))
There is code here that is just "noise" for the PR. If there are no significant changes, please do not change the spacing / formatting.

2023-05-01 14:15 UTC, LiNk-NY requested changes
Hi Dario, @drighelli 
Can you address the first comment in the previous review?
I think that one is the only necessary change.
Thank you.

2023-05-02 16:43 UTC, merged

2023-05-03 09:13 UTC, drighelli commented
Hi Marcel, @LiNk-NY 

I think the comment was already fixed, am I missing something?

2023-05-03 16:12 UTC, LiNk-NY commented
Hi Dario, @drighelli  
I took care of it.

2023-05-03 19:42 UTC, drighelli commented
oh ok! sorry about that!