Cord blood mtd
waldronlab/SingleCellMultiModal pull request #62
Opened 2023-05-09 15:46 UTC by drighelli

adding metadata/colData for cord_blood dataset in CITEseq.

providing rda object through slack.

2023-05-09 18:20 UTC, LiNk-NY approved these changes

2023-05-09 18:20 UTC, LiNk-NY commented on R/CITEseq.R
> +        if (filtered==TRUE) {
This should be `if (filtered)`

2023-05-09 18:20 UTC, LiNk-NY commented
Thank Dario @drighelli , it looks good.

2023-05-10 08:32 UTC, drighelli commented on R/CITEseq.R
> +        if (filtered==TRUE) {
right! will be fixed in the next commit!

2023-05-14 15:53 UTC, drighelli commented
I can see that the latest commits on peripheral_blood dataset are already tracked in this PR.

2023-05-15 16:35 UTC, LiNk-NY commented
Hi Dario, @drighelli 
I don't see an entry in the metadata for the `peripheral_blood/v1.0.0/scRNAseq_coldata.rda`. Can you add this?

2023-05-15 16:41 UTC, LiNk-NY requested changes
Please include an additional entry in the metadata for the `peripheral_blood` colData Rda file. Everything else looks good. Thanks

2023-05-15 17:05 UTC, drighelli commented
ahah sorry I edited the file without pushing it. 

check it now please! 

Thanks for the review!

2023-05-16 14:24 UTC, LiNk-NY approved these changes

2023-05-16 15:20 UTC, merged

2023-05-16 22:47 UTC, LiNk-NY commented
I'm still waiting on the updated database but the changes have been merged.